// ─────────────────────────────────────────────────────────────────────────────
//  backgroundTheme.js — LEGACY / UNUSED
//
//  The active runtime theme system is src/utils/timeGradient.js.
//  This file is intentionally left in place as historical reference only.
//  Do not edit this file for live day/sunset/night behaviour unless App.jsx is
//  changed to import getBackgroundTheme() again.
//
//  Maps { timeOfDay, weather } → CSS custom-property values.
//
//  HOW IT FITS IN
//  ──────────────
//  • Legacy flow: App.jsx called getBackgroundTheme() and wrote returned values
//    to :root inline styles plus data-time / data-atm attributes.
//  • index.css reads --bg-deep (body base colour), --atm-glow-1/2 (radial blobs),
//    and the data-time attribute for the complete token swap.
//
//  TIME BUCKETS (visual atmospheres)
//  ──────────────────────────────────
//  morning   06:00–11:00  →  airy white-blue sky
//  afternoon 11:00–17:00  →  clear bright sky
//  sunset    17:00–20:00  →  warm peach/amber golden hour ← NEW
//  night     20:00–06:00  →  deep cinematic navy
//
//  WEATHER INFLUENCE
//  ──────────────────
//  Rainy/stormy overrides → muted/darker variants.
//  Cloudy → softer, greyer.
//  Sunny → default (each period's default is its "sunny" palette).
// ─────────────────────────────────────────────────────────────────────────────

export function getTimeOfDay(hour) {
  if (hour >= 6  && hour < 11) return 'morning'    // 6 am – 11 am
  if (hour >= 11 && hour < 17) return 'afternoon'  // 11 am – 5 pm
  if (hour >= 17 && hour < 20) return 'sunset'     // 5 pm – 8 pm  ← golden hour
  return 'night'                                    // 8 pm – 6 am
}

// ── Palette table ─────────────────────────────────────────────────────────────
//
//  bgDeep  → --bg-deep  (body background-color; CSS-transitions over 1.8s)
//  glow1   → --atm-glow-1  (radial blob, top-left)
//  glow2   → --atm-glow-2  (radial blob, bottom-right)
//
//  Night/sunset:  bgDeep is dark; text tokens stay light.
//  Day (light):   bgDeep is light; [data-time="day"] swaps text to dark.
//  Sunset:        bgDeep is light-warm; [data-time="sunset"] swaps text to dark.

const THEMES = {

  // ── Morning · sunny / clear ────────────────────────────────────────────────
  morning_sunny: {
    bgDeep: '#e2f2ff',
    glow1:  'rgba(90, 175, 255, 0.50)',
    glow2:  'rgba(180, 225, 255, 0.38)',
  },
  afternoon_sunny: {
    bgDeep: '#d8edff',
    glow1:  'rgba(80, 168, 255, 0.46)',
    glow2:  'rgba(165, 215, 255, 0.32)',
  },

  // ── Morning · overcast / rain ──────────────────────────────────────────────
  morning_cloudy: {
    bgDeep: '#e4eaf5',
    glow1:  'rgba(140, 160, 220, 0.28)',
    glow2:  'rgba(115, 138, 200, 0.20)',
  },
  afternoon_cloudy: {
    bgDeep: '#e8ecf7',
    glow1:  'rgba(130, 152, 215, 0.24)',
    glow2:  'rgba(110, 132, 195, 0.18)',
  },
  morning_rainy: {
    bgDeep: '#d2dff0',
    glow1:  'rgba(80, 115, 210, 0.28)',
    glow2:  'rgba(60,  90, 185, 0.20)',
  },
  afternoon_rainy: {
    bgDeep: '#ccd9ec',
    glow1:  'rgba(70, 110, 210, 0.30)',
    glow2:  'rgba(55,  85, 190, 0.22)',
  },

  // ── Sunset / golden hour ───────────────────────────────────────────────────
  // Light warm palette — text flips dark via [data-time="sunset"].
  // Modals stay dark warm glass (see index.css --glass-modal override).
  sunset_sunny: {
    bgDeep: '#ffd8b0',                    // warm peach — matches gradient midpoint
    glow1:  'rgba(255, 140, 55, 0.62)',   // strong amber glow
    glow2:  'rgba(220, 75, 120, 0.38)',   // soft rose / pink
  },
  sunset_cloudy: {
    bgDeep: '#f5c8a0',
    glow1:  'rgba(220, 110, 48, 0.48)',
    glow2:  'rgba(185, 68, 108, 0.30)',
  },
  sunset_rainy: {
    bgDeep: '#e8b090',                    // muted warm peach
    glow1:  'rgba(180, 80, 38, 0.38)',
    glow2:  'rgba(145, 58, 95, 0.25)',
  },

  // ── Night ──────────────────────────────────────────────────────────────────
  night: {
    bgDeep: '#050812',
    glow1:  'rgba(100, 80, 205, 0.08)',
    glow2:  'rgba(70,  60, 175, 0.05)',
  },
  night_rainy: {
    bgDeep: '#040810',
    glow1:  'rgba(60, 95, 200, 0.11)',
    glow2:  'rgba(50, 80, 185, 0.06)',
  },
}

// ── Main export ───────────────────────────────────────────────────────────────

export function getBackgroundTheme({ timeOfDay, weather }) {
  const isRainy  = weather === 'rain' || weather === 'storm'
  const isCloudy = weather === 'cloudy' || weather === 'fog' || weather === 'snow'

  const isDaytime = timeOfDay === 'morning' || timeOfDay === 'afternoon'
  const isSunset  = timeOfDay === 'sunset'

  let theme
  if (timeOfDay === 'morning') {
    theme = isRainy ? THEMES.morning_rainy
          : isCloudy ? THEMES.morning_cloudy
          : THEMES.morning_sunny
  } else if (timeOfDay === 'afternoon') {
    theme = isRainy ? THEMES.afternoon_rainy
          : isCloudy ? THEMES.afternoon_cloudy
          : THEMES.afternoon_sunny
  } else if (timeOfDay === 'sunset') {
    theme = isRainy ? THEMES.sunset_rainy
          : isCloudy ? THEMES.sunset_cloudy
          : THEMES.sunset_sunny
  } else {
    // night (8 pm – 6 am)
    theme = isRainy ? THEMES.night_rainy : THEMES.night
  }

  return { ...theme, isDaytime, isSunset }
}
